### ISSUE TITLE
Error while requiring the library: Declaration of Fiddler\Composer\AutoloadGenerator::getAutoloadRealFile() should be compatible with Composer\Autoload\AutoloadGenerator::getAutoloadRealFile()

### ISSUE THREAD

**Issue by ribeiropaulor** [beberlei/composer-monorepo-plugin#29]
The following error is happening while only requiring the library in an empty directory.

<img width="1354" alt="captura de tela 2016-05-18 as 07 02 39" src="https://cloud.githubusercontent.com/assets/376830/15354989/bfe317a2-1cc6-11e6-914b-0e91f74f798b.png">

**Comment by ribeiropaulor** [comment]
Last month the method `AutoloadGenerator::getAutoloadRealFile()` was updated. It's added a last parameter `$staticPhpVersion = 70000`. See the commit https://github.com/composer/composer/commit/40aca80bd9eddb6219f8c5cc05193b26f52e27ee#diff-33037407f7f293f37df2258567b56598.

**Comment by beberlei** [comment]
Fixed in #28
