### ISSUE TITLE
Use relative over absolute symlinks for binary files

### ISSUE THREAD

**Issue by tPl0ch** [beberlei/composer-monorepo-plugin#30]
Currently the `Build.php` script uses an absolute path to symlink the binary files. This breaks setups with shared filesystems that maybe mounted on different directories between the hosts (i.e. vagrant shared directories).

It would be nice to be able to use relative paths within the symlink which would solve these issues.

I am currently thinking about adding a `$relative` parameter to PHP's symlink/link functions in order to behave analogous to `ln -sr TARGET LINKNAME`. Using `exec("ln -sr $absolutePath $linkPath")` will yield the correct relative result, but I think this solution is very hacky and not preferable. And using some custom logic to calculate the relative path between the target seems overkill. Not sure what to do best here though.

**Comment by cfuerst** [comment]
+1 do u need help with anything here?
