### ISSUE TITLE
Monorepo with multiple symfony applications

### ISSUE THREAD

**Issue by kbond** [beberlei/composer-monorepo-plugin#36]
I am trying to switch from manyrepos to a monorepo and am trying out this plugin. I have several symfony apps and component libraries I am trying to combine. I have got all the autoloading working but am looking for suggestions on using [incenteev/composer-parameter-handler](https://github.com/Incenteev/ParameterHandler).

It looks like my parameters need to be defined in the root composer.json. Should I define all the parameters in a single `parameters.yml` and all apps will draw from this global file?

I'm just looking to see if anyone else has come across this and how they solved it.

**Comment by beberlei** [comment]
@kbond sorry, i don't use composer-parameter-handler, installation requiring interaction from users is really bad practice IMHO, because it makes automation harder. My dev application has a parameters.yml that just works and its exchanged for staging and production.

**Comment by kbond** [comment]
Ok. For the record, I don't use the interactive mode. I use the `env-map` option to map to environment variables. Specifically when deploying to Heroku so everything is highly automated.
