### ISSUE TITLE
AutoloadGenerator.php messes up order of autoloading

### ISSUE THREAD

**Issue by dopeh** [beberlei/composer-monorepo-plugin#38]
Introduced in this commit[0] is a change to use require_once instead of require for files in autoload_files.php. However, this change messes up the order of how files are being loaded. Normally the require('autoload_files.php') is at the end of the getLoader() method, so by the time it's called, all other autoloading is done (classmap has been loaded, etc). Instead, the autoload_files.php is included as soon as the autoload_real.php is included, while the getLoader() method has not been called yet.
So by the time autoload_files.php is called, none of the classes are available yet and you can only run code that does not need to autoload anything.
If any of the files in autoload_files.php want to use a class that's being autoloaded, it's no longer possible. 

Is there a specific reason to use require_once specifically over the default composer way?

To reproduce:
- Add a file to be autoloaded with composer to monorepo.json:

`"autoload": {
        "files": [
            "my_custom_autoload.php"
        ]
    }`
- In my_custom_autoload.php attempt to access a class in one of your dependencies (e.g. symfony)

Expected: class from vendor dir can be loaded without problem
Result: fatal error because autoloader has not been executed yet.

[0] https://github.com/beberlei/composer-monorepo-plugin/commit/86bacda4dd18ddfe57c24a2c0b0552562d8e594e

**Comment by zkiiito** [comment]
Unfortunately, it also breaks on this code, which we have as a dependency:
https://github.com/symfony/polyfill-php72/blob/master/bootstrap.php#L29

because this way the bootstrap file is required before autoloading had been set up, and this way can not find the p\Php72 class.

**Comment by Ekman** [comment]
Having the same issue. Basically, it is [this override](https://github.com/beberlei/composer-monorepo-plugin/blob/master/src/main/Monorepo/Composer/AutoloadGenerator.php#L19) that is causing the issue.
