### ISSUE TITLE
composer monorepo:build breaks with composer version 2.2.6

### ISSUE THREAD

**Issue by calinblaga** [beberlei/composer-monorepo-plugin#75]
I'm getting this error `Fatal error: Class Monorepo\Composer\MonorepoInstalledRepository contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Composer\Repository\InstalledRepositoryInterface::getDevMode) in /var/www/html/vendor/beberlei/composer-monorepo-plugin/src/main/Monorepo/Composer/MonorepoInstalledRepository.php on line 9` when running `composer monorepo:build`
Composer version 2.2.6 2022-02-04 17:00:38

**Comment by tabomgui** [comment]
I have this issue too, can u solve that? @calinblaga

**Comment by qualeo** [comment]
@calinblaga @hengenguilherme I am experiencing this error too in the latest `master`. However, it appears that @Ekman already submitted https://github.com/beberlei/composer-monorepo-plugin/pull/73 to address this. What do you think, @beberlei?

**Comment by beberlei** [comment]
Merged #73

**Comment by unional** [comment]
Looks like the build failed and this is not released?
